name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            exe: .exe
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            exe: .exe
          # macOS
          - target: x86_64-apple-darwin
            os: macos-latest
            exe: ""
          - target: aarch64-apple-darwin
            os: macos-latest
            exe: ""
          # Linux (using older Ubuntu for better GLIBC compatibility)
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            exe: ""
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            exe: ""
          # Linux with MUSL (static linking, no GLIBC dependency)
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            exe: ""
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            exe: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools (Linux)
        if: matrix.os == 'ubuntu-latest' && (matrix.target == 'aarch64-unknown-linux-gnu' || matrix.target == 'aarch64-unknown-linux-musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install MUSL tools
        if: matrix.os == 'ubuntu-latest' && contains(matrix.target, 'musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
          if [[ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]]; then
            sudo ln -sf /usr/bin/musl-gcc /usr/local/bin/x86_64-linux-musl-gcc
          elif [[ "${{ matrix.target }}" == "aarch64-unknown-linux-musl" ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
            # Create a wrapper for aarch64 musl gcc
            echo '#!/bin/bash' | sudo tee /usr/local/bin/aarch64-linux-musl-gcc
            echo 'exec aarch64-linux-gnu-gcc "$@"' | sudo tee -a /usr/local/bin/aarch64-linux-musl-gcc
            sudo chmod +x /usr/local/bin/aarch64-linux-musl-gcc
          fi

      - name: Configure cross-compilation (Linux ARM64)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          mkdir -p ~/.cargo
          echo '[target.aarch64-unknown-linux-gnu]' >> ~/.cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml

      - name: Configure cross-compilation (Linux ARM64 MUSL)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-musl'
        run: |
          mkdir -p ~/.cargo
          echo '[target.aarch64-unknown-linux-musl]' >> ~/.cargo/config.toml
          echo 'linker = "aarch64-linux-musl-gcc"' >> ~/.cargo/config.toml

      - name: Configure cross-compilation (Linux x86_64 MUSL)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          mkdir -p ~/.cargo
          echo '[target.x86_64-unknown-linux-musl]' >> ~/.cargo/config.toml
          echo 'linker = "x86_64-linux-musl-gcc"' >> ~/.cargo/config.toml

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
            ${{ runner.os }}-cargo-

      - name: Build binary
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == *"musl"* && "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # For MUSL targets on Linux, enable static linking
            export RUSTFLAGS="-C target-feature=+crt-static"
          fi
          cargo build --release --target ${{ matrix.target }}

      - name: Create archive name
        id: archive
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            echo "name=rustory-${{ matrix.target }}.zip" >> $GITHUB_OUTPUT
          else
            echo "name=rustory-${{ matrix.target }}.tar.gz" >> $GITHUB_OUTPUT
          fi

      - name: Create archive (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../${{ steps.archive.outputs.name }} rustory${{ matrix.exe }}

      - name: Create archive (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf ../../../${{ steps.archive.outputs.name }} rustory${{ matrix.exe }}

      - name: Generate SHA256
        id: sha256
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            hash=$(sha256sum ${{ steps.archive.outputs.name }} | cut -d ' ' -f 1)
          else
            hash=$(shasum -a 256 ${{ steps.archive.outputs.name }} | cut -d ' ' -f 1)
          fi
          echo "hash=$hash" >> $GITHUB_OUTPUT
          echo "${{ steps.archive.outputs.name }} \`$hash\`" > sha256.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.archive.outputs.name }}
          path: |
            ${{ steps.archive.outputs.name }}
            sha256.txt

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -la artifacts/

      - name: Prepare release files
        run: |
          mkdir -p release
          find artifacts -type f \( -name "*.zip" -o -name "*.tar.gz" \) | while read file; do
            cp "$file" release/
          done

      - name: Generate SHA256 list
        id: sha256-list
        run: |
          echo "## SHA256 Checksums" > SHA256SUMS.txt
          find artifacts -name "sha256.txt" | sort | while read file; do
            cat "$file" | while read line; do
              echo "- $line" >> SHA256SUMS.txt
            done
          done
          cat SHA256SUMS.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*
          body_path: SHA256SUMS.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
